import { Button } from "antd";

export default function SelectedProduct() {
  const product = [
    {
      id: 1,
      name: "womans_fashion",
      img: "",
      title: "",
      original_cost: 230,
      cost: 280,
      star: 249,
      discount:"-40%",
    },
    {
        id: 2,
        name: "womans_fashion",
        img: "",
        title: "",
        original_cost: 230,
        cost: 280,
        star: 249,
        discount:"-40%",
      },
      {
        id: 3,
        name: "womans_fashion",
        img: "",
        title: "",
        original_cost: 230,
        cost: 280,
        star: 249,
        discount:"-40%",
      },
      {
        id: 4,
        name: "womans_fashion",
        img: "",
        title: "",
        original_cost: 230,
        cost: 280,
        star: 249,
        discount:"-40%",
      },
      {
        id: 5,
        name: "womans_fashion",
        img: "",
        title: "",
        original_cost: 230,
        cost: 280,
        star: 249,
        discount:"-40%",
      },
      {
        id: 6,
        name: "womans_fashion",
        img: "",
        title: "",
        original_cost: 230,
        cost: 280,
        star: 249,
        discount:"-40%",
      },
      {
        id: 7,
        name: "womans_fashion",
        img: "",
        title: "",
        original_cost: 230,
        cost: 280,
        star: 249,
        discount:"-40%",
      },
      {
        id: 8,
        name: "womans_fashion",
        img: "",
        title: "",
        original_cost: 230,
        cost: 280,
        star: 249,
        discount:"-40%",
      },
      {
        id: 9,
        name: "womans_fashion",
        img: "",
        title: "",
        original_cost: 230,
        cost: 280,
        star: 249,
        discount:"-40%",
      },
      {
        id: 10,
        name: "womans_fashion",
        img: "",
        title: "",
        original_cost: 230,
        cost: 280,
        star: 249,
        discount:"-40%",
      },
      {
        id: 11,
        name: "womans_fashion",
        img: "",
        title: "",
        original_cost: 230,
        cost: 280,
        star: 249,
        discount:"-40%",
      },
      {
        id: 12,
        name: "womans_fashion",
        img: "",
        title: "",
        original_cost: 230,
        cost: 280,
        star: 249,
        discount:"-40%",
      },
      {
        id: 13,
        name: "womans_fashion",
        img: "",
        title: "",
        original_cost: 230,
        cost: 280,
        star: 249,
        discount:"-40%",
      },
      {
        id: 14,
        name: "womans_fashion",
        img: "",
        title: "",
        original_cost: 230,
        cost: 280,
        star: 249,
        discount:"-40%",
      },
      {
        id: 15,
        name: "womans_fashion",
        img: "",
        title: "",
        original_cost: 230,
        cost: 280,
        star: 249,
        discount:"-40%",
      },
      {
        id: 16,
        name: "womans_fashion",
        img: "",
        title: "",
        original_cost: 230,
        cost: 280,
        star: 249,
        discount:"-40%",
      },
      {
        id: 17,
        name: "womans_fashion",
        img: "",
        title: "",
        original_cost: 230,
        cost: 280,
        star: 249,
        discount:"-40%",
      },
      {
        id: 18,
        name: "womans_fashion",
        img: "",
        title: "",
        original_cost: 230,
        cost: 280,
        star: 249,
        discount:"-40%",
      },

  ];

  return <div>This is selected product</div>;
}
